# Generated by Django 6.0.5 on 2026-05-18 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('senha_hash', models.CharField(max_length=256)),
                ('cargo', models.CharField(choices=[('dono', 'Dono'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default='funcionario', max_length=20)),
                ('pontos', models.IntegerField(default=0)),
                ('meta_mensal', models.IntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RemocaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_removidos', models.IntegerField()),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remocoes', to='core.funcionario')),
                ('removido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remocoes_realizadas', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Remoção de Pontos',
                'verbose_name_plural': 'Remoções de Pontos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('pontos', models.IntegerField(default=10)),
                ('prazo', models.DateTimeField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('aceita', 'Aceita'), ('pendente_finalizacao', 'Aguardando Aprovação'), ('finalizada', 'Finalizada')], default='disponivel', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('aceita_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_aceitas', to='core.funcionario')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criadas', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
