# Generated by Django 6.0.5 on 2026-05-26 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('aceita', 'Aceita'), ('pendente_finalizacao', 'Aguardando Aprovação'), ('finalizada', 'Finalizada'), ('expirada', 'Expirada')], default='disponivel', max_length=30),
        ),
        migrations.CreateModel(
            name='AdicaoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_adicionados', models.IntegerField()),
                ('motivo', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('adicionado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adicoes_realizadas', to='core.funcionario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adicoes', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Adição de Pontos',
                'verbose_name_plural': 'Adições de Pontos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='TarefaRecorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('pontos', models.IntegerField(default=10)),
                ('dias_semana', models.CharField(max_length=20)),
                ('horario_limite', models.TimeField()),
                ('ativa', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_recorrentes_criadas', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Tarefa Recorrente',
                'verbose_name_plural': 'Tarefas Recorrentes',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='tarefa',
            name='recorrente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_geradas', to='core.tarefarecorrente'),
        ),
    ]
