# Generated by Django 5.0.3 on 2026-07-01 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tarefa_status_adicaopontos_tarefarecorrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='mes_referencia',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.CreateModel(
            name='HistoricoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_ano', models.CharField(max_length=7)),
                ('pontos_finais', models.IntegerField()),
                ('meta', models.IntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='core.funcionario')),
            ],
            options={
                'verbose_name': 'Histórico Mensal',
                'verbose_name_plural': 'Históricos Mensais',
                'ordering': ['-mes_ano'],
            },
        ),
    ]
